//
// Created by yanghuichen on 2020-08-09.
//

#ifndef LINUX_PROGRAMMING_ENAME_H
#define LINUX_PROGRAMMING_ENAME_H

static char *ename[] = {
        "EPERM", "ENOENT", "ESRCH", "EINTR", "EIO", "ENXIO", "E2BIG",
        "ENOEXEC", "EBADF", "ECHILD", "EAGAIN/EWOULDBLOCK", "ENOMEM",
        "EACCES", "EFAULT", "ENOTBLK", "EBUSY", "EEXIST", "EXDEV",
        "ENODEV", "ENOTDIR", "EISDIR", "EINVAL", "ENFILE", "EMFILE",
        "ENOTTY", "ETXTBSY", "EFBIG", "ENOSPC", "ESPIPE", "EROFS",
        "EMLINK", "EPIPE", "EDOM", "ERANGE", "EDEADLK/EDEADLOCK",
        "ENAMETOOLONG", "ENOLCK", "ENOSYS", "ENOTEMPTY", "ELOOP", "",
        "ENOMSG", "EIDRM", "ECHRNG", "EL2NSYNC", "EL3HLT", "EL3RST",
        "ELNRNG", "EUNATCH", "ENOCSI", "EL2HLT", "EBADE", "EBADR",
        "EXFULL", "ENOANO", "EBADRQC", "EBADSLT", "", "EBFONT", "ENOSTR",
        "ENODATA", "ETIME", "ENOSR", "ENONET", "ENOPKG", "EREMOTE",
        "ENOLINK", "EADV", "ESRMNT", "ECOMM", "EPROTO", "EMULTIHOP",
        "EDOTDOT", "EBADMSG", "EOVERFLOW", "ENOTUNIQ", "EBADFD",
        "EREMCHG", "ELIBACC", "ELIBBAD", "ELIBSCN", "ELIBMAX",
        "ELIBEXEC", "EILSEQ", "ERESTART", "ESTRPIPE", "EUSERS",
        "ENOTSOCK", "EDESTADDRREQ", "EMSGSIZE", "EPROTOTYPE",
        "ENOPROTOOPT", "EPROTONOSUPPORT", "ESOCKTNOSUPPORT",
        "EOPNOTSUPP/ENOTSUP", "EPFNOSUPPORT", "EAFNOSUPPORT",
        "EADDRINUSE", "EADDRNOTAVAIL", "ENETDOWN", "ENETUNREACH",
        "ENETRESET", "ECONNABORTED", "ECONNRESET", "ENOBUFS", "EISCONN",
        "ENOTCONN", "ESHUTDOWN", "ETOOMANYREFS", "ETIMEDOUT",
        "ECONNREFUSED", "EHOSTDOWN", "EHOSTUNREACH", "EALREADY",
        "EINPROGRESS", "ESTALE", "EUCLEAN", "ENOTNAM", "ENAVAIL",
        "EISNAM", "EREMOTEIO", "EDQUOT", "ENOMEDIUM", "EMEDIUMTYPE",
        "ECANCELED", "ENOKEY", "EKEYEXPIRED", "EKEYREVOKED",
        "EKEYREJECTED", "EOWNERDEAD", "ENOTRECOVERABLE", "ERFKILL"
};

#define MAX_ENAME 132

#endif //LINUX_PROGRAMMING_ENAME_H
